name: angular storybook

on:
  push:
    branches: ["**"]
    paths:
      - "TypeScript/Storybook/**"
      #- "**"
  pull_request:
    branches: ["main"]
    paths:
      - "TypeScript/Storybook/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: CI
        run: cd TypeScript/Storybook && npm ci

      - name: Test
        run: cd TypeScript/Storybook && npm test
