# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Elegant code .net

on:
  push:
    branches: ["**"]
    paths:
      - "c#/ElegantCode/**"
  pull_request:
    branches: ["main"]
    paths:
      - "c#/ElegantCode/**"
jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
 
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '17'   

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install .NET MAUI
        run: dotnet workload install maui


      # - name: Install .NET MAUI
      #   run: |
      #     dotnet nuget locals all --clear
      #     dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
      #     dotnet workload install android ios maccatalyst macos maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
      - name: Restore dependencies
        run: cd c#/ElegantCode && dotnet restore
      - name: Build
        run: cd c#/ElegantCode && dotnet build --no-restore
      - name: Test
        run: cd c#/ElegantCode && dotnet test --no-build --verbosity normal
