name: rpgTypeScriptTu

on:
  push:
    branches: ["features/*", "main"]
    paths:
      #- "TypeScript/Rpg/**"
      - "**"
  pull_request:
    branches: ["main"]
    paths:
      - "TypeScript/Rpg/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          #cache: "TypeScript/Rpg/package-lock.json"
      - run: cd TypeScript/Rpg
      - run: npm ci
      - run: npm test
      #- run: npm run build --if-present
      #- run: npm test
